name: "Getting CodePush Deployment Action"
decription: "This action get deployment information using code push cli. if you use only code push cli, get specific deployment with deployment name."
inputs:
  appcenter-token:
    description: "Access token for using code push cli"
    required: true
  deployment-name:
    description: "Deployment name for selecting from many deployments related app"
    required: true
  app-name:
    description: "Specify app in the <ownerName>/<appName> format"
    required: true
outputs:
  deployment:
    description: "Deployment JSON object by code push deployment CLI"
runs:
  using: "node16"
  main: "index.js"
